CREATE SCHEMA IF NOT EXISTS MANDATUM.RAW;
CREATE SCHEMA IF NOT EXISTS MANDATUM.TPCH_SF_1;
CREATE SCHEMA IF NOT EXISTS MANDATUM.STG;

GRANT ALL ON ALL TABLES IN SCHEMA MANDATUM.RAW to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA MANDATUM.RAW to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA MANDATUM.TPCH_SF_1 to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA MANDATUM.TPCH_SF_1 to ROLE transform;
GRANT ALL ON ALL TABLES IN SCHEMA MANDATUM.STG to ROLE transform;
GRANT ALL ON FUTURE TABLES IN SCHEMA MANDATUM.STG to ROLE transform;


-- Set up the defaults
USE WAREHOUSE COMPUTE_WH;
USE DATABASE MANDATUM;
USE SCHEMA TPCH_SF_1;

CREATE OR REPLACE TABLE MB_CUSTOMER (
      C_CUSTKEY INTEGER,
      C_NAME STRING,
      C_ADDRESS STRING,
      C_NATIONKEY INTEGER,
      C_PHONE STRING,
      C_ACCTBAL DECIMAL(10,2),
      C_MKTSEGMENT STRING,
      C_COMMENT STRING);

CREATE OR REPLACE TABLE MB_LINEITEM (
      L_ORDERKEY INTEGER,
      L_PARTKEY INTEGER,
      L_SUPPKEY INTEGER,
      L_LINENUMBER INTEGER,
      L_QUANTITY INTEGER,
      L_EXTENDEDPRICE DECIMAL(10,2),
      L_DISCOUNT DECIMAL(2,2),
      L_TAX DECIMAL(2,2),
      L_RETURNFLAG STRING,
      L_LINESTATUS STRING,
      L_SHIPDATE STRING,
      L_COMMITDATE STRING,
      L_RECEIPTDATE STRING,
      L_SHIPINSTRUCT STRING,
      L_SHIPMODE STRING,
      L_COMMENT STRING);

CREATE OR REPLACE TABLE MB_NATION(
      N_NATIONKEY INTEGER,
      N_NAME STRING,
      N_REGIONKEY INTEGER,
      N_COMMENT STRING);

CREATE OR REPLACE TABLE MB_ORDERS (
      O_ORDERKEY INTEGER,
      O_CUSTKEY INTEGER,
      O_ORDERSTATUS STRING,
      O_TOTALPRICE DECIMAL(10,2),
      O_ORDERDATE DATE,
      O_ORDERPRIORITY STRING,
      O_CLERK STRING,
      O_SHIPPRIORITY INTEGER,
      O_COMMENT STRING);

CREATE OR REPLACE TABLE MB_PART (
      P_PARTKEY INTEGER,
      P_NAME STRING,
      P_MFGR STRING,
      P_BRAND STRING,
      P_TYPE STRING,
      P_SIZE INTEGER,
      P_CONTAINER STRING,
      P_RETAILPRICE DECIMAL(10,2),
      P_COMMENT STRING);

CREATE OR REPLACE TABLE MB_PARTSUPP (
      PS_PARTKEY INTEGER,
      PS_SUPPKEY INTEGER,
      PS_AVAILQTY INTEGER,
      PS_SUPPLYCOST FLOAT,
      PS_COMMENT STRING);

CREATE OR REPLACE TABLE MB_REGION (
      R_REGIONKEY INTEGER,
      R_NAME STRING,
      R_COMMENT STRING);

CREATE OR REPLACE TABLE MB_SUPPLIER (
      S_SUPPKEY INTEGER,
      S_NAME STRING,
      S_ADDRESS STRING,
      S_NATIONKEY INTEGER,
      S_PHONE STRING,
      S_ACCTBAL DECIMAL(10,2),
      S_COMMENT STRING);


insert into MB_CUSTOMER
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.CUSTOMER;

insert into MB_LINEITEM
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.LINEITEM;

insert into MB_NATION
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.NATION;

insert into MB_orders
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.ORDERS;

insert into MB_part
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PART;

insert into MB_partsupp
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.PARTSUPP;

insert into MB_region
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.REGION;

insert into MB_supplier
select * from SNOWFLAKE_SAMPLE_DATA.TPCH_SF1.SUPPLIER;

