SELECT
    a.C_CUSTKEY AS CUSTOMER_KEY,
    a.C_NAME AS CUSTOMER_NAME,
    a.C_ADDRESS AS CUSTOMER_ADDRESS,
    a.C_NATIONKEY AS CUSTOMER_NATION_KEY,
    a.C_PHONE AS CUSTOMER_PHONE,
    a.C_ACCTBAL AS CUSTOMER_ACCBAL,
    a.C_MKTSEGMENT AS CUSTOMER_MKTSEGMENT,
    a.C_COMMENT AS CUSTOMER_COMMENT,
    b.L_USERNAME AS LOGIN_USER_NAME,
    b.L_NATIONKEY AS LOGIN_NATION_KEY,
    b.L_LOGINTIMESTAMP AS LOGIN_TIMESTAMP
FROM {{ source('raw_data', 'raw_customer') }} a
INNER JOIN {{ source('raw_data', 'raw_login') }} b
    ON a.C_CUSTKEY = b.L_USERKEY
